name: RunTests

on: [push, pull_request]

jobs:
  test_frontend:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ['10', '12', '14', '16']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Cache npm
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ matrix.node }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: |
        npm install

    - name: Run tests
      run: |
        npm run test

  deploy_frontend:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['16']
    runs-on: ${{ matrix.os }}
    needs: [test_frontend]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Cache npm
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ matrix.node }}-node-production-${{ hashFiles('**/package-lock.json') }}

    - name: Install npm dependencies
      run: |
        npm install --production

    - name: Build
      run: |
        npm run build

    - name: Publish to Github Pages
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_PAGES_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.
